"""******************************************************************************************
  Assembly:                Mathy
  Filename:                forecasting.py
  Author:                  Terry D. Eppler
  Created:                 08-31-2025

  Last Modified By:        Terry D. Eppler
  Last Modified On:        08-31-2025
******************************************************************************************
<copyright file="forecasting.py" company="Terry D. Eppler">

     Mathy Models

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the “Software”),
 to deal in the Software without restriction,
 including without limitation the rights to use,
 copy, modify, merge, publish, distribute, sublicense,
 and/or sell copies of the Software,
 and to permit persons to whom the Software is furnished to do so,
 subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.
 IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 DEALINGS IN THE SOFTWARE.

 You can contact me at:  terryeppler@gmail.com or eppler.terry@epa.gov

</copyright>
<summary>
    Provides time-series forecasting, cross-validation, lag-feature modeling, ARIMA,
    SARIMA, gradient-boosted lag regression, and quantile lag-regression wrappers for
    Mathy forecasting workflows. The module standardizes training, projection, scoring,
    and residual-diagnostic operations across statsmodels and sklearn estimators.
</summary>
******************************************************************************************
"""
from __future__ import annotations
from boogr import Error, Logger
from typing import Optional, Dict, Generator, Tuple
import numpy as np
import statsmodels.tsa.statespace.sarimax as st
import statsmodels.tsa.arima.model as am
import statsmodels.api as sm
from matplotlib import pyplot as plt
from sklearn.metrics import (mean_squared_error, mean_absolute_error, max_error,
                             median_absolute_error, explained_variance_score, r2_score)
from statsmodels.regression.linear_model import RegressionResultsWrapper
import sklearn.ensemble as ske
import sklearn.linear_model as skl

def throw_if( name: str, value: object ) -> None:
	"""Validate a required forecasting argument.

		Purpose:
		    Enforces the presence of required time-series inputs, fitted models, design matrices,
		    and forecast parameters before model execution. The validation accepts populated NumPy
		    arrays and standard Python containers while rejecting null values and empty collections
		    that cannot support training, projection, scoring, cross-validation, or diagnostic
		    calculations.

		Args:
		    name: Argument name used in the validation error message.
		    value: Argument value checked for a null or empty state.

		Raises:
		    ValueError: Raised when `value` is None or empty.
	"""
	if value is None:
		raise ValueError( f'Argument "{name}" cannot be empty!' )
	
	if isinstance( value, np.ndarray ) and value.size == 0:
		raise ValueError( f'Argument "{name}" cannot be empty!' )
	
	if isinstance( value, (str, list, tuple, dict, set) ) and len( value ) == 0:
		raise ValueError( f'Argument "{name}" cannot be empty!' )

class TimeSeries( ):
	"""Share time-series state.

		Purpose:
		    Provides the base runtime attributes used by forecasting wrappers that train on ordered
		    observations, store fitted target values, and retain the most recent forecast output.
		    The class supplies a minimal common state contract for concrete time-series estimators.

		Attributes:
		    training_data: Feature matrix or lagged design matrix used for training.
		    tranining_values: Target values aligned to the training matrix.
		    prediction: Most recent forecast or projection generated by the model.
	"""
	training_data: Optional[ np.ndarray ]
	tranining_values: Optional[ np.ndarray ]
	prediction: Optional[ np.ndarray ]
	
	def __init__( self ):
		self.training_data = None
		self.tranining_values = None
		self.prediction = None

class ExpandingWindow( ):
	"""Create expanding-window validation splits.

		Purpose:
		    Generates forward-chaining train/test indices for time-series validation where each
		    successive training window expands over time and each test window remains fixed in size.
		    The splitter preserves temporal order, supports optional gaps, and exposes sklearn-style
		    split-count and visualization helpers.

		Attributes:
		    initial_window: Number of observations included in the first training window.
		    test_window: Number of observations included in each testing window.
		    max_splits: Maximum number of splits produced by the generator.
		    n_splits: sklearn-style split count override.
		    max_train_size: Optional cap on the length of each training window.
		    gap: Number of observations skipped between each train and test segment.
	"""
	initial_window: int
	test_window: int
	max_splits: Optional[ int ]
	n_splits: Optional[ int ]
	max_train_size: Optional[ int ]
	gap: int
	
	def __init__( self, initial: int = 30, windows: int = 10, splits: int | None = None,
			n_splits: int | None = None, max_train_size: int | None = None,
			test_size: int | None = None, gap: int = 0 ) -> None:
		"""Initialize expanding-window splitter.

				Purpose:
				    Configures the first training-window size, test-window size, split limit, optional train-size cap, sklearn-style split count, and temporal gap used to produce forward-chaining validation indices.

				Args:
				    initial: Number of observations in the first training window.
				    windows: Number of observations in each testing window.
				    splits: Legacy maximum number of expanding-window splits.
				    n_splits: sklearn-style maximum number of validation splits.
				    max_train_size: Optional cap applied to each training-window length.
				    test_size: Optional sklearn-style test-window size override.
				    gap: Number of observations skipped between train and test windows.
		"""
		self.initial_window = int( initial )
		self.test_window = int( test_size ) if test_size is not None else int( windows )
		self.max_splits = int( splits ) if splits is not None else None
		self.n_splits = int( n_splits ) if n_splits is not None else self.max_splits
		self.max_train_size = int( max_train_size ) if max_train_size is not None else None
		self.gap = int( gap )
	
	def split( self, series: np.ndarray, y: np.ndarray = None,
			groups: np.ndarray = None ) -> Generator[ Tuple[ np.ndarray, np.ndarray ], None, None ]:
		"""Yield expanding-window splits.

				Purpose:
				    Generates chronological train and test index arrays from a one-dimensional time-series input using the configured expanding-window rules.

				Args:
				    series: Ordered observations used to determine split boundaries.
				    y: Optional target array accepted for sklearn splitter compatibility.
				    groups: Optional group labels accepted for sklearn splitter compatibility.

				Returns:
				    Generator[Tuple[np.ndarray, np.ndarray], None, None]: Generator[Tuple[np.ndarray, np.ndarray], None, None] returned by the forecasting operation.

				Raises:
				    Error: Raised when validation, model execution, forecasting, scoring, or diagnostic calculation fails.
		"""
		try:
			throw_if( 'series', series )
			values = np.asarray( series ).reshape( -1 )
			n_obs = len( values )
			
			if self.initial_window < 1:
				raise ValueError( 'Argument "initial" must be greater than zero.' )
			
			if self.test_window < 1:
				raise ValueError( 'Argument "test_size" must be greater than zero.' )
			
			if self.gap < 0:
				raise ValueError( 'Argument "gap" cannot be negative.' )
			
			if self.max_train_size is not None and self.max_train_size < 1:
				raise ValueError( 'Argument "max_train_size" must be greater than zero.' )
			
			if self.n_splits is not None and self.n_splits < 1:
				raise ValueError( 'Argument "n_splits" must be greater than zero.' )
			
			if self.initial_window + self.gap + self.test_window > n_obs:
				message = (
						'Argument "series" does not contain enough observations for the '
						'requested initial window, gap, and test size.'
				)
				raise ValueError( message )
			
			split_count = 0
			train_stop = self.initial_window
			
			while (train_stop + self.gap + self.test_window) <= n_obs:
				if self.max_train_size is None:
					train_start = 0
				else:
					train_start = max( 0, train_stop - self.max_train_size )
				
				test_start = train_stop + self.gap
				test_stop = test_start + self.test_window
				
				train_idx = np.arange( train_start, train_stop, dtype=int )
				test_idx = np.arange( test_start, test_stop, dtype=int )
				
				if len( train_idx ) == 0 or len( test_idx ) == 0:
					break
				
				yield train_idx, test_idx
				
				split_count += 1
				if self.n_splits is not None and split_count >= self.n_splits:
					break
				
				train_stop = test_stop
		except Exception as e:
			exception = Error( e )
			exception.module = 'mathy'
			exception.cause = 'ExpandingWindow'
			exception.method = 'split( self, *args ) -> Generator[Tuple[np.ndarray, np.ndarray], None, None]'
			Logger( ).write( exception )
			raise exception
	
	def get_splits( self, series: np.ndarray ) -> list[ Tuple[ np.ndarray, np.ndarray ] ]:
		"""Materialize expanding-window splits.

				Purpose:
				    Collects all expanding-window train/test index pairs into a list for inspection, repeated use, or plotting.

				Args:
				    series: Ordered observations used to determine split boundaries.

				Returns:
				    list[Tuple[np.ndarray, np.ndarray]]: list[Tuple[np.ndarray, np.ndarray]] returned by the forecasting operation.

				Raises:
				    Error: Raised when validation, model execution, forecasting, scoring, or diagnostic calculation fails.
		"""
		try:
			throw_if( 'series', series )
			return list( self.split( series ) )
		except Exception as e:
			exception = Error( e )
			exception.module = 'mathy'
			exception.cause = 'ExpandingWindow'
			exception.method = 'get_splits( self, series: np.ndarray ) -> list[Tuple[np.ndarray, np.ndarray]]'
			Logger( ).write( exception )
			raise exception
	
	def get_n_splits( self, series: Optional[ np.ndarray ] = None,
			y: Optional[ np.ndarray ] = None, groups: Optional[ np.ndarray ] = None ) -> int:
		"""Count expanding-window splits.

				Purpose:
				    Returns the number of validation splits that the expanding-window splitter will produce for the supplied series and configuration.

				Args:
				    series: Optional ordered observations used to calculate available splits.
				    y: Optional target array accepted for sklearn splitter compatibility.
				    groups: Optional group labels accepted for sklearn splitter compatibility.

				Returns:
				    int: int returned by the forecasting operation.

				Raises:
				    Error: Raised when validation, model execution, forecasting, scoring, or diagnostic calculation fails.
		"""
		try:
			if series is None:
				if self.n_splits is not None:
					return int( self.n_splits )
				
				raise ValueError(
					'Argument "series" is required when the number of splits is not '
					'explicitly configured.'
				)
			
			throw_if( 'series', series )
			return len( list( self.split( series ) ) )
		except Exception as e:
			exception = Error( e )
			exception.module = 'mathy'
			exception.cause = 'ExpandingWindow'
			exception.method = 'get_n_splits( self, *args ) -> int'
			Logger( ).write( exception )
			raise exception
	
	def visualize( self, series: np.ndarray ) -> plt.Figure | None:
		"""Visualize expanding-window splits.

				Purpose:
				    Builds a matplotlib figure showing the chronological train and test windows produced by the expanding-window splitter.

				Args:
				    series: Ordered observations used to generate the split visualization.

				Returns:
				    plt.Figure | None: plt.Figure | None returned by the forecasting operation.

				Raises:
				    Error: Raised when validation, model execution, forecasting, scoring, or diagnostic calculation fails.
		"""
		try:
			throw_if( 'series', series )
			values = np.asarray( series, dtype=float ).reshape( -1 )
			splits = self.get_splits( values )
			
			if not splits:
				raise ValueError( 'No train/test splits were generated for visualization.' )
			
			n_splits = len( splits )
			fig, axes = plt.subplots( n_splits, 1, figsize=(10, 2.5 * n_splits) )
			
			if n_splits == 1:
				axes = [ axes ]
			
			x_axis = np.arange( len( values ) )
			
			for i, (train_idx, test_idx) in enumerate( splits ):
				axis = axes[ i ]
				axis.plot( x_axis[ train_idx ], values[ train_idx ], label='Train' )
				axis.plot( x_axis[ test_idx ], values[ test_idx ], label='Test' )
				axis.set_title( f'Split {i + 1}' )
				axis.legend( )
				axis.grid( True, alpha=0.25 )
			
			plt.tight_layout( )
			return fig
		except Exception as e:
			exception = Error( e )
			exception.module = 'mathy'
			exception.cause = 'ExpandingWindow'
			exception.method = 'visualize( self, series: np.ndarray ) -> plt.Figure | None'
			Logger( ).write( exception )
			raise exception

class TimeSeriesSpliter( ):
	"""Create fixed-window time-series validation splits.

		Purpose:
		    Produces sklearn-style time-series cross-validation indices using a requested number of
		    splits, optional training-window cap, optional test-window size, and optional temporal gap.
		    The splitter maintains chronological ordering and supports split materialization and
		    visualization for model-validation workflows.

		Attributes:
		    splits: Number of chronological validation splits to generate.
		    max_train_size: Optional cap on each training-window length.
		    test_size: Optional number of observations in each test segment.
		    gap: Number of observations skipped between train and test segments.
	"""
	n_splits: int
	max_train_size: Optional[ int ]
	test_size: Optional[ int ]
	gap: int
	
	def __init__( self, splits: int = 5, max_train_size: Optional[ int ] = None,
			test_size: Optional[ int ] = None, gap: int = 0 ) -> None:
		"""Initialize time-series splitter.

				Purpose:
				    Configures the number of chronological splits, optional maximum training size, optional fixed test size, and temporal gap used by the fixed-window splitter.

				Args:
				    splits: Number of chronological validation splits.
				    max_train_size: Optional cap applied to each training-window length.
				    test_size: Optional number of observations in each testing window.
				    gap: Number of observations skipped between train and test windows.
		"""
		self.n_splits = int( splits )
		self.max_train_size = max_train_size
		self.test_size = test_size
		self.gap = int( gap )
	
	def split( self, series: np.ndarray, y: np.ndarray = None,
			groups: np.ndarray = None ) -> Generator[ Tuple[ np.ndarray, np.ndarray ], None, None ]:
		"""Yield time-series splits.

				Purpose:
				    Generates chronological train and test index arrays from a one-dimensional time-series input using the configured fixed-window split rules.

				Args:
				    series: Ordered observations used to determine split boundaries.
				    y: Optional target array accepted for sklearn splitter compatibility.
				    groups: Optional group labels accepted for sklearn splitter compatibility.

				Returns:
				    Generator[Tuple[np.ndarray, np.ndarray], None, None]: Generator[Tuple[np.ndarray, np.ndarray], None, None] returned by the forecasting operation.

				Raises:
				    Error: Raised when validation, model execution, forecasting, scoring, or diagnostic calculation fails.
		"""
		try:
			throw_if( 'series', series )
			
			values = np.asarray( series ).reshape( -1 )
			n_samples = len( values )
			
			if self.n_splits < 2:
				raise ValueError( 'Argument "splits" must be at least 2.' )
			
			if self.gap < 0:
				raise ValueError( 'Argument "gap" cannot be negative.' )
			
			if self.max_train_size is not None and self.max_train_size < 1:
				raise ValueError( 'Argument "max_train_size" must be greater than zero.' )
			
			if self.test_size is None:
				computed_test_size = n_samples // (self.n_splits + 1)
			else:
				computed_test_size = int( self.test_size )
			
			if computed_test_size < 1:
				raise ValueError( 'Argument "test_size" must be greater than zero.' )
			
			required = self.n_splits * computed_test_size + self.gap
			if required >= n_samples:
				raise ValueError(
					'The series does not contain enough observations for the '
					'requested number of splits, test size, and gap.'
				)
			
			test_starts = range( n_samples - (self.n_splits * computed_test_size),
				n_samples, computed_test_size )
			
			for test_start in test_starts:
				train_end = test_start - self.gap
				
				if train_end <= 0:
					raise ValueError(
						'The requested gap leaves no observations available for training.'
					)
				
				if self.max_train_size is not None and self.max_train_size < train_end:
					train_start = train_end - self.max_train_size
				else:
					train_start = 0
				
				train_index = np.arange( train_start, train_end, dtype=int )
				test_index = np.arange( test_start,
					min( test_start + computed_test_size, n_samples ), dtype=int )
				
				if len( train_index ) == 0 or len( test_index ) == 0:
					continue
				
				yield train_index, test_index
		except Exception as e:
			exception = Error( e )
			exception.module = 'mathy'
			exception.cause = 'TimeSeriesSpliter'
			exception.method = 'split( self, *args ) -> Generator[Tuple[np.ndarray, np.ndarray], None, None]'
			Logger( ).write( exception )
			raise exception
	
	def get_n_splits( self, series: np.ndarray = None,
			y: np.ndarray = None, groups: np.ndarray = None ) -> int | None:
		"""Count time-series splits.

				Purpose:
				    Returns the configured number of chronological validation splits available for the supplied series and splitter configuration.

				Args:
				    series: Optional ordered observations used to validate split availability.
				    y: Optional target array accepted for sklearn splitter compatibility.
				    groups: Optional group labels accepted for sklearn splitter compatibility.

				Returns:
				    int | None: int | None returned by the forecasting operation.

				Raises:
				    Error: Raised when validation, model execution, forecasting, scoring, or diagnostic calculation fails.
		"""
		try:
			return self.n_splits
		except Exception as e:
			exception = Error( e )
			exception.module = 'mathy'
			exception.cause = 'TimeSeriesSpliter'
			exception.method = 'get_n_splits( self, *args ) -> int | None'
			Logger( ).write( exception )
			raise exception
	
	def get_splits( self, series: np.ndarray ) -> list[ Tuple[ np.ndarray, np.ndarray ] ]:
		"""Materialize time-series splits.

				Purpose:
				    Collects all chronological train/test index pairs into a list for inspection, repeated use, or plotting.

				Args:
				    series: Ordered observations used to determine split boundaries.

				Returns:
				    list[Tuple[np.ndarray, np.ndarray]]: list[Tuple[np.ndarray, np.ndarray]] returned by the forecasting operation.

				Raises:
				    Error: Raised when validation, model execution, forecasting, scoring, or diagnostic calculation fails.
		"""
		try:
			throw_if( 'series', series )
			return list( self.split( series ) )
		except Exception as e:
			exception = Error( e )
			exception.module = 'mathy'
			exception.cause = 'TimeSeriesSpliter'
			exception.method = 'get_splits( self, series: np.ndarray ) -> list[Tuple[np.ndarray, np.ndarray]]'
			Logger( ).write( exception )
			raise exception
	
	def visualize( self, series: np.ndarray ) -> plt.Figure | None:
		"""Visualize time-series splits.

				Purpose:
				    Builds a matplotlib figure showing the chronological train and test windows produced by the fixed-window splitter.

				Args:
				    series: Ordered observations used to generate the split visualization.

				Returns:
				    plt.Figure | None: plt.Figure | None returned by the forecasting operation.

				Raises:
				    Error: Raised when validation, model execution, forecasting, scoring, or diagnostic calculation fails.
		"""
		try:
			throw_if( 'series', series )
			values = np.asarray( series, dtype=float ).reshape( -1 )
			splits = self.get_splits( values )
			
			if not splits:
				raise ValueError( 'No time-series splits were generated.' )
			
			fig, axes = plt.subplots( len( splits ), 1, figsize=(10, 2.5 * len( splits )) )
			
			if len( splits ) == 1:
				axes = [ axes ]
			
			x_axis = np.arange( len( values ) )
			
			for i, (train_idx, test_idx) in enumerate( splits ):
				axis = axes[ i ]
				axis.plot( x_axis[ train_idx ], values[ train_idx ], label='Train' )
				axis.plot( x_axis[ test_idx ], values[ test_idx ], label='Test' )
				axis.set_title( f'Split {i + 1}' )
				axis.grid( True, alpha=0.25 )
				axis.legend( )
			
			plt.tight_layout( )
			return fig
		except Exception as e:
			exception = Error( e )
			exception.module = 'mathy'
			exception.cause = 'TimeSeriesSpliter'
			exception.method = 'visualize( self, series: np.ndarray ) -> plt.Figure | None'
			Logger( ).write( exception )
			raise exception

class LaggingSeries( TimeSeries ):
	"""Forecast with linear lag features.

		Purpose:
			Builds lagged supervised-learning matrices from univariate time-series observations,
			trains a linear regression model on historical lag windows, projects future values
			recursively, and reports regression metrics for fitted lag forecasts.

		Attributes:
			lag: Number of lagged observations used as predictors.
			model: Linear regression estimator trained on lagged features.
			training_data: Lagged feature matrix produced from the source series.
			tranining_values: Target vector aligned to lagged feature rows.
			prediction: Most recent recursive forecast output.
	"""
	model: Optional[ RegressionResultsWrapper ]
	lag: int
	prediction: Optional[ np.ndarray ]
	training_data: Optional[ np.ndarray ]
	training_values: Optional[ np.ndarray ]
	design_matrix: Optional[ np.ndarray ]
	
	def __init__( self, lag: int = 5 ) -> None:
		"""Initialize linear lag forecaster.

				Purpose:
					Configures the lag-window length, constructs the linear regression estimator, and prepares training, target, and prediction caches for lag-based forecasting.

				Args:
					lag: Number of lagged observations used as predictors.
		"""
		self.lag = lag
		self.model = None
		self.prediction = None
		self.training_data = None
		self.training_values = None
		self.design_matrix = None
	
	def lag_transform( self, series: np.ndarray ) -> Tuple[ np.ndarray, np.ndarray ]:
		"""Create lagged training arrays.

				Purpose:
					Converts an ordered univariate series into a supervised-learning design matrix where each row contains lagged observations and each target value contains the next observation.

				Args:
					series: Ordered univariate series used to create lagged features and targets.

				Returns:
					Tuple[np.ndarray, np.ndarray]: Tuple[np.ndarray, np.ndarray] returned by the forecasting operation.

				Raises:
					Error: Raised when validation, model execution, forecasting, scoring, or diagnostic calculation fails.
		"""
		try:
			throw_if( 'series', series )
			if len( series ) <= self.lag:
				raise ValueError(
					f'Argument "series" must contain more than {self.lag} observations.' )
			
			values = np.asarray( series, dtype=float ).reshape( -1 )
			n = len( values )
			self.training_data = np.array(
				[ values[ i - self.lag:i ] for i in range( self.lag, n ) ],
				dtype=float )
			self.training_values = values[ self.lag: ]
			return self.training_data, self.training_values
		except Exception as e:
			exception = Error( e )
			exception.module = 'mathy'
			exception.cause = 'LaggingSeries'
			exception.method = 'lag_transform( self, series: np.ndarray ) -> Tuple[np.ndarray, np.ndarray]'
			Logger( ).write( exception )
			raise exception
	
	def train( self, series: np.ndarray ) -> LaggingSeries | None:
		"""Fit LaggingSeries model.

				Purpose:
					Fits the forecasting estimator to lagged features generated from the supplied time series and stores the training matrix and aligned target vector on the wrapper.

				Args:
					series: Ordered univariate series used to train the lag-based forecasting model.

				Returns:
					LaggingSeries | None: LaggingSeries | None returned by the forecasting operation.

				Raises:
					Error: Raised when validation, model execution, forecasting, scoring, or diagnostic calculation fails.
		"""
		try:
			throw_if( 'series', series )
			x_data, y_data = self.lag_transform( series )
			self.design_matrix = sm.add_constant( x_data, has_constant='add' )
			self.model = sm.OLS( y_data, self.design_matrix ).fit( )
			return self
		except Exception as e:
			exception = Error( e )
			exception.module = 'mathy'
			exception.cause = 'LaggingSeries'
			exception.method = 'train( self, series: np.ndarray ) -> LaggingSeries | None'
			Logger( ).write( exception )
			raise exception
	
	def project( self, n_steps: int = 1 ) -> np.ndarray:
		"""Project future observations.

				Purpose:
					Generates recursive forward forecasts by feeding each newly predicted value back into the lag window for subsequent forecast steps.

				Args:
					n_steps: Number of future periods to forecast.

				Returns:
					np.ndarray: np.ndarray returned by the forecasting operation.

				Raises:
					Error: Raised when validation, model execution, forecasting, scoring, or diagnostic calculation fails.
		"""
		try:
			throw_if( 'n_steps', n_steps )
			throw_if( 'training_data', self.training_data )
			throw_if( 'model', self.model )
			if n_steps < 1:
				raise ValueError( 'Argument "n_steps" must be greater than zero.' )
			
			last_window = self.training_data[ -1 ].astype( float ).copy( )
			preds = [ ]
			for _ in range( n_steps ):
				x_input = sm.add_constant( last_window.reshape( 1, -1 ), has_constant='add' )
				next_value = float( self.model.predict( x_input )[ 0 ] )
				preds.append( next_value )
				last_window = np.roll( last_window, -1 )
				last_window[ -1 ] = next_value
			
			self.prediction = np.array( preds, dtype=float )
			return self.prediction
		except Exception as e:
			exception = Error( e )
			exception.module = 'mathy'
			exception.cause = 'LaggingSeries'
			exception.method = 'project( self, n_steps: int=1 ) -> np.ndarray'
			Logger( ).write( exception )
			raise exception
	
	def score( self ) -> float | None:
		"""Score fitted forecasts.

				Purpose:
					Computes the coefficient of determination for fitted in-sample predictions against the stored training target values.

				Returns:
					float | None: float | None returned by the forecasting operation.

				Raises:
					Error: Raised when validation, model execution, forecasting, scoring, or diagnostic calculation fails.
		"""
		try:
			throw_if( 'model', self.model )
			return float( self.model.rsquared )
		except Exception as e:
			exception = Error( e )
			exception.module = 'mathy'
			exception.cause = 'LaggingSeries'
			exception.method = 'score( self ) -> float | None'
			Logger( ).write( exception )
			raise exception
	
	def analyze( self ) -> Dict[ str, float ] | None:
		"""Analyze forecast residuals.

				Purpose:
					Computes regression diagnostics for fitted in-sample predictions, including squared error, absolute error, explained variance, maximum error, median absolute error, and coefficient of determination.

				Returns:
					Dict[str, float] | None: Dict[str, float] | None returned by the forecasting operation.

				Raises:
					Error: Raised when validation, model execution, forecasting, scoring, or diagnostic calculation fails.
		"""
		try:
			throw_if( 'training_values', self.training_values )
			throw_if( 'design_matrix', self.design_matrix )
			throw_if( 'model', self.model )
			self.prediction = np.asarray( self.model.predict( self.design_matrix ), dtype=float )
			return { 'MSE': mean_squared_error( self.training_values, self.prediction ),
			         'RMSE': np.sqrt( mean_squared_error( self.training_values, self.prediction ) ),
			         'MAE': mean_absolute_error( self.training_values, self.prediction ),
			         'MedianAE': median_absolute_error( self.training_values, self.prediction ),
			         'R2': r2_score( self.training_values, self.prediction ),
			         'ExplainedVariance': explained_variance_score( self.training_values,
				         self.prediction ) }
		except Exception as e:
			exception = Error( e )
			exception.module = 'mathy'
			exception.cause = 'LaggingSeries'
			exception.method = 'analyze( self ) -> Dict[str, float] | None'
			Logger( ).write( exception )
			raise exception

class LagBoostingSeries( TimeSeries ):
	"""Forecast with histogram gradient boosting over lag features.

		Purpose:
		    Builds lagged supervised-learning matrices and trains a histogram gradient boosting
		    regressor for nonlinear time-series forecasting. The wrapper exposes the estimator
		    configuration, recursive multi-step projection, and regression diagnostics for the
		    fitted lag model.

		Attributes:
		    lag: Number of lagged observations used as predictors.
		    model: Boosting estimator trained on lagged features.
		    training_data: Lagged feature matrix produced from the source series.
		    tranining_values: Target vector aligned to lagged feature rows.
		    prediction: Most recent recursive forecast output.
	"""
	model: Optional[ ske.HistGradientBoostingRegressor ]
	lag: int
	loss: str
	quantile: Optional[ float ]
	learning_rate: float
	max_iter: int
	max_leaf_nodes: Optional[ int ]
	max_depth: Optional[ int ]
	min_samples_leaf: int
	l2_regularization: float
	max_features: float
	max_bins: int
	monotonic_cst: Optional[ object ]
	interaction_cst: Optional[ object ]
	warm_start: bool
	early_stopping: str | bool
	scoring: str
	validation_fraction: float
	n_iter_no_change: int
	tol: float
	verbose: int
	random_state: Optional[ int ]
	training_values: Optional[ np.ndarray ]
	fitted_values: Optional[ np.ndarray ]
	mean_absolute_error: Optional[ float ]
	mean_squared_error: Optional[ float ]
	root_mean_squared_error: Optional[ float ]
	r2_score: Optional[ float ]
	explained_variance_score: Optional[ float ]
	median_absolute_error: Optional[ float ]
	max_error: Optional[ float ]
	
	def __init__( self, lag: int = 12, loss: str = 'squared_error',
			quantile: Optional[ float ] = None, rate: float = 0.1,
			iters: int = 100, leaf_nodes: Optional[ int ] = 31,
			depth: Optional[ int ] = None, leaf: int = 20,
			regularization: float = 0.0, features: float = 1.0,
			bins: int = 255, monotonic: Optional[ object ] = None,
			interaction: Optional[ object ] = None, warm: bool = False,
			stopping: str | bool = 'auto', scoring: str = 'loss',
			validation: float = 0.1, no_change: int = 10,
			tol: float = 1e-7, verbose: int = 0,
			rando: Optional[ int ] = None ) -> None:
		"""Initialize boosting lag forecaster.

				Purpose:
				    Configures the lag-window length and histogram gradient boosting regression options used for nonlinear recursive time-series forecasting.

				Args:
				    lag: Number of lagged observations used as predictors.
				    loss: Loss function used by the boosting regressor.
				    quantile: Quantile value used when quantile loss is selected.
				    rate: Learning rate for boosting updates.
				    iters: Maximum number of boosting iterations.
				    leaf_nodes: Maximum number of leaf nodes per tree.
				    depth: Maximum tree depth.
				    leaf: Minimum samples per leaf.
				    regularization: L2 regularization strength.
				    features: Fraction or count of features considered per split.
				    bins: Maximum number of histogram bins.
				    monotonic: Monotonic constraint configuration.
				    interaction: Interaction constraint configuration.
				    warm: Flag indicating whether warm-start fitting is enabled.
				    stopping: Early-stopping mode.
				    scoring: Scoring metric used for early stopping.
				    validation: Validation fraction used for early stopping.
				    no_change: Iterations without improvement allowed before stopping.
				    tol: Tolerance used for early-stopping improvement checks.
				    verbose: Verbosity level passed to the estimator.
				    rando: Random seed passed to the estimator.
		"""
		super( ).__init__( )
		self.lag = lag
		self.loss = loss
		self.quantile = quantile
		self.learning_rate = rate
		self.max_iter = iters
		self.max_leaf_nodes = leaf_nodes
		self.max_depth = depth
		self.min_samples_leaf = leaf
		self.l2_regularization = regularization
		self.max_features = features
		self.max_bins = bins
		self.monotonic_cst = monotonic
		self.interaction_cst = interaction
		self.warm_start = warm
		self.early_stopping = stopping
		self.scoring = scoring
		self.validation_fraction = validation
		self.n_iter_no_change = no_change
		self.tol = tol
		self.verbose = verbose
		self.random_state = rando
		self.model = ske.HistGradientBoostingRegressor( loss=self.loss, quantile=self.quantile,
			learning_rate=self.learning_rate, max_iter=self.max_iter,
			max_leaf_nodes=self.max_leaf_nodes, max_depth=self.max_depth,
			min_samples_leaf=self.min_samples_leaf, l2_regularization=self.l2_regularization,
			max_features=self.max_features, max_bins=self.max_bins,
			monotonic_cst=self.monotonic_cst, interaction_cst=self.interaction_cst,
			warm_start=self.warm_start, early_stopping=self.early_stopping, scoring=self.scoring,
			validation_fraction=self.validation_fraction, n_iter_no_change=self.n_iter_no_change,
			tol=self.tol, verbose=self.verbose, random_state=self.random_state )
		self.training_data = None
		self.training_values = None
		self.prediction = None
		self.fitted_values = None
		self.mean_absolute_error = 0.0
		self.mean_squared_error = 0.0
		self.root_mean_squared_error = 0.0
		self.r2_score = 0.0
		self.explained_variance_score = 0.0
		self.median_absolute_error = 0.0
		self.max_error = 0.0
	
	def lag_transform( self, series: np.ndarray ) -> Tuple[ np.ndarray, np.ndarray ]:
		"""Create lagged training arrays.

				Purpose:
				    Converts an ordered univariate series into a supervised-learning design matrix where each row contains lagged observations and each target value contains the next observation.

				Args:
				    series: Ordered univariate series used to create lagged features and targets.

				Returns:
				    Tuple[np.ndarray, np.ndarray]: Tuple[np.ndarray, np.ndarray] returned by the forecasting operation.

				Raises:
				    Error: Raised when validation, model execution, forecasting, scoring, or diagnostic calculation fails.
		"""
		try:
			throw_if( 'series', series )
			
			if self.lag < 1:
				raise ValueError( 'Argument "lag" must be greater than zero.' )
			
			values = np.asarray( series, dtype=float ).reshape( -1 )
			if len( values ) <= self.lag:
				raise ValueError(
					f'Argument "series" must contain more than {self.lag} observations.'
				)
			
			self.training_data = np.array(
				[ values[ i - self.lag:i ] for i in range( self.lag, len( values ) ) ],
				dtype=float )
			
			self.training_values = values[ self.lag: ]
			return self.training_data, self.training_values
		except Exception as e:
			exception = Error( e )
			exception.module = 'mathy'
			exception.cause = 'LagBoostingSeries'
			exception.method = 'lag_transform( self, series: np.ndarray ) -> Tuple[np.ndarray, np.ndarray]'
			Logger( ).write( exception )
			raise exception
	
	def train( self, series: np.ndarray ) -> LagBoostingSeries | None:
		"""Fit LagBoostingSeries model.

				Purpose:
				    Fits the forecasting estimator to lagged features generated from the supplied time series and stores the training matrix and aligned target vector on the wrapper.

				Args:
				    series: Ordered univariate series used to train the lag-based forecasting model.

				Returns:
				    LagBoostingSeries | None: LagBoostingSeries | None returned by the forecasting operation.

				Raises:
				    Error: Raised when validation, model execution, forecasting, scoring, or diagnostic calculation fails.
		"""
		try:
			throw_if( 'series', series )
			
			if self.loss == 'quantile' and self.quantile is None:
				raise ValueError(
					'Argument "quantile" is required when loss is "quantile".'
				)
			
			x_data, y_data = self.lag_transform( series )
			self.model.fit( x_data, y_data )
			self.fitted_values = self.model.predict( x_data )
			self.prediction = None
			return self
		except Exception as e:
			exception = Error( e )
			exception.module = 'mathy'
			exception.cause = 'LagBoostingSeries'
			exception.method = 'train( self, series: np.ndarray ) -> LagBoostingSeries | None'
			Logger( ).write( exception )
			raise exception
	
	def project( self, n_steps: int = 1 ) -> np.ndarray | None:
		"""Project future observations.

				Purpose:
				    Generates recursive forward forecasts by feeding each newly predicted value back into the lag window for subsequent forecast steps.

				Args:
				    n_steps: Number of future periods to forecast.

				Returns:
				    np.ndarray | None: np.ndarray | None returned by the forecasting operation.

				Raises:
				    Error: Raised when validation, model execution, forecasting, scoring, or diagnostic calculation fails.
		"""
		try:
			throw_if( 'n_steps', n_steps )
			throw_if( 'training_data', self.training_data )
			throw_if( 'model', self.model )
			
			if n_steps < 1:
				raise ValueError( 'Argument "n_steps" must be greater than zero.' )
			
			last_window = self.training_data[ -1 ].astype( float ).copy( )
			preds = [ ]
			
			for _ in range( n_steps ):
				next_value = float( self.model.predict( last_window.reshape( 1, -1 ) )[ 0 ] )
				preds.append( next_value )
				last_window = np.roll( last_window, -1 )
				last_window[ -1 ] = next_value
			
			self.prediction = np.array( preds, dtype=float )
			return self.prediction
		except Exception as e:
			exception = Error( e )
			exception.module = 'mathy'
			exception.cause = 'LagBoostingSeries'
			exception.method = 'project( self, n_steps: int=1 ) -> np.ndarray | None'
			Logger( ).write( exception )
			raise exception
	
	def score( self ) -> float | None:
		"""Score fitted forecasts.

				Purpose:
				    Computes the coefficient of determination for fitted in-sample predictions against the stored training target values.

				Returns:
				    float | None: float | None returned by the forecasting operation.

				Raises:
				    Error: Raised when validation, model execution, forecasting, scoring, or diagnostic calculation fails.
		"""
		try:
			throw_if( 'training_data', self.training_data )
			throw_if( 'training_values', self.training_values )
			return float( self.model.score( self.training_data, self.training_values ) )
		except Exception as e:
			exception = Error( e )
			exception.module = 'mathy'
			exception.cause = 'LagBoostingSeries'
			exception.method = 'score( self ) -> float | None'
			Logger( ).write( exception )
			raise exception
	
	def analyze( self ) -> Dict[ str, float ] | None:
		"""Analyze forecast residuals.

				Purpose:
				    Computes regression diagnostics for fitted in-sample predictions, including squared error, absolute error, explained variance, maximum error, median absolute error, and coefficient of determination.

				Returns:
				    Dict[str, float] | None: Dict[str, float] | None returned by the forecasting operation.

				Raises:
				    Error: Raised when validation, model execution, forecasting, scoring, or diagnostic calculation fails.
		"""
		try:
			throw_if( 'training_values', self.training_values )
			
			if self.fitted_values is None:
				throw_if( 'training_data', self.training_data )
				self.fitted_values = self.model.predict( self.training_data )
			
			self.mean_absolute_error = mean_absolute_error( self.training_values,
				self.fitted_values )
			
			self.mean_squared_error = mean_squared_error( self.training_values,
				self.fitted_values )
			
			self.root_mean_squared_error = float( np.sqrt( self.mean_squared_error ) )
			self.r2_score = r2_score( self.training_values, self.fitted_values )
			self.explained_variance_score = explained_variance_score( self.training_values,
				self.fitted_values )
			
			self.median_absolute_error = median_absolute_error(
				self.training_values,
				self.fitted_values
			)
			self.max_error = max_error(
				self.training_values,
				self.fitted_values
			)
			
			return {
					'MAE': float( self.mean_absolute_error ),
					'MSE': float( self.mean_squared_error ),
					'RMSE': float( self.root_mean_squared_error ),
					'R2': float( self.r2_score ),
					'EVS': float( self.explained_variance_score ),
					'MedianAE': float( self.median_absolute_error ),
					'MAX': float( self.max_error )
			}
		except Exception as e:
			exception = Error( e )
			exception.module = 'mathy'
			exception.cause = 'LagBoostingSeries'
			exception.method = 'analyze( self ) -> Dict[str, float] | None'
			Logger( ).write( exception )
			raise exception

class LagQuantileSeries( TimeSeries ):
	"""Forecast quantiles with lag features.

		Purpose:
		    Builds lagged supervised-learning matrices and trains a quantile regression estimator
		    for conditional quantile forecasting. The wrapper supports recursive projection and
		    regression diagnostics for median, lower-tail, or upper-tail time-series forecasts.

		Attributes:
		    lag: Number of lagged observations used as predictors.
		    quantile: Conditional quantile estimated by the regression model.
		    alpha: L1 regularization strength passed to sklearn QuantileRegressor.
		    model: Quantile regression estimator trained on lagged features.
		    training_data: Lagged feature matrix produced from the source series.
		    tranining_values: Target vector aligned to lagged feature rows.
		    prediction: Most recent recursive forecast output.
	"""
	model: Optional[ skl.QuantileRegressor ]
	lag: int
	quantile: float
	alpha: float
	fit_intercept: bool
	solver: str
	solver_options: Optional[ Dict[ str, object ] ]
	training_values: Optional[ np.ndarray ]
	fitted_values: Optional[ np.ndarray ]
	mean_absolute_error: Optional[ float ]
	mean_squared_error: Optional[ float ]
	root_mean_squared_error: Optional[ float ]
	r2_score: Optional[ float ]
	explained_variance_score: Optional[ float ]
	median_absolute_error: Optional[ float ]
	max_error: Optional[ float ]
	
	def __init__( self, lag: int = 12, quantile: float = 0.5, alpha: float = 1.0,
			fit: bool = True, solver: str = 'highs',
			solver_options: Optional[ Dict[ str, object ] ] = None ) -> None:
		"""Initialize quantile lag forecaster.

				Purpose:
				    Configures the lag-window length and quantile regression options used to estimate conditional quantiles from lagged time-series features.

				Args:
				    lag: Number of lagged observations used as predictors.
				    quantile: Conditional quantile estimated by the model.
				    alpha: L1 regularization strength.
				    fit: Flag indicating whether an intercept is fitted.
				    solver: Linear programming solver used by QuantileRegressor.
				    solver_options: Optional solver-specific configuration dictionary.
		"""
		super( ).__init__( )
		self.lag = lag
		self.quantile = quantile
		self.alpha = alpha
		self.fit_intercept = fit
		self.solver = solver
		self.solver_options = solver_options
		self.model = skl.QuantileRegressor(
			quantile=self.quantile,
			alpha=self.alpha,
			fit_intercept=self.fit_intercept,
			solver=self.solver,
			solver_options=self.solver_options
		)
		self.training_data = None
		self.training_values = None
		self.prediction = None
		self.fitted_values = None
		self.mean_absolute_error = 0.0
		self.mean_squared_error = 0.0
		self.root_mean_squared_error = 0.0
		self.r2_score = 0.0
		self.explained_variance_score = 0.0
		self.median_absolute_error = 0.0
		self.max_error = 0.0
	
	def lag_transform( self, series: np.ndarray ) -> Tuple[ np.ndarray, np.ndarray ]:
		"""Create lagged training arrays.

				Purpose:
				    Converts an ordered univariate series into a supervised-learning design matrix where each row contains lagged observations and each target value contains the next observation.

				Args:
				    series: Ordered univariate series used to create lagged features and targets.

				Returns:
				    Tuple[np.ndarray, np.ndarray]: Tuple[np.ndarray, np.ndarray] returned by the forecasting operation.

				Raises:
				    Error: Raised when validation, model execution, forecasting, scoring, or diagnostic calculation fails.
		"""
		try:
			throw_if( 'series', series )
			
			if self.lag < 1:
				raise ValueError( 'Argument "lag" must be greater than zero.' )
			
			values = np.asarray( series, dtype=float ).reshape( -1 )
			if len( values ) <= self.lag:
				raise ValueError(
					f'Argument "series" must contain more than {self.lag} observations.'
				)
			
			self.training_data = np.array(
				[ values[ i - self.lag:i ] for i in range( self.lag, len( values ) ) ],
				dtype=float
			)
			self.training_values = values[ self.lag: ]
			return self.training_data, self.training_values
		except Exception as e:
			exception = Error( e )
			exception.module = 'mathy'
			exception.cause = 'LagQuantileSeries'
			exception.method = 'lag_transform( self, series: np.ndarray ) -> Tuple[np.ndarray, np.ndarray]'
			Logger( ).write( exception )
			raise exception
	
	def train( self, series: np.ndarray ) -> LagQuantileSeries | None:
		"""Fit LagQuantileSeries model.

				Purpose:
				    Fits the forecasting estimator to lagged features generated from the supplied time series and stores the training matrix and aligned target vector on the wrapper.

				Args:
				    series: Ordered univariate series used to train the lag-based forecasting model.

				Returns:
				    LagQuantileSeries | None: LagQuantileSeries | None returned by the forecasting operation.

				Raises:
				    Error: Raised when validation, model execution, forecasting, scoring, or diagnostic calculation fails.
		"""
		try:
			throw_if( 'series', series )
			
			if self.quantile <= 0.0 or self.quantile >= 1.0:
				raise ValueError(
					'Argument "quantile" must be strictly between 0 and 1.'
				)
			
			if self.alpha < 0.0:
				raise ValueError( 'Argument "alpha" cannot be negative.' )
			
			x_data, y_data = self.lag_transform( series )
			self.model.fit( x_data, y_data )
			self.fitted_values = self.model.predict( x_data )
			self.prediction = None
			return self
		except Exception as e:
			exception = Error( e )
			exception.module = 'mathy'
			exception.cause = 'LagQuantileSeries'
			exception.method = 'train( self, series: np.ndarray ) -> LagQuantileSeries | None'
			Logger( ).write( exception )
			raise exception
	
	def project( self, n_steps: int = 1 ) -> np.ndarray | None:
		"""Project future observations.

				Purpose:
				    Generates recursive forward forecasts by feeding each newly predicted value back into the lag window for subsequent forecast steps.

				Args:
				    n_steps: Number of future periods to forecast.

				Returns:
				    np.ndarray | None: np.ndarray | None returned by the forecasting operation.

				Raises:
				    Error: Raised when validation, model execution, forecasting, scoring, or diagnostic calculation fails.
		"""
		try:
			throw_if( 'n_steps', n_steps )
			throw_if( 'training_data', self.training_data )
			throw_if( 'model', self.model )
			
			if n_steps < 1:
				raise ValueError( 'Argument "n_steps" must be greater than zero.' )
			
			last_window = self.training_data[ -1 ].astype( float ).copy( )
			preds = [ ]
			
			for _ in range( n_steps ):
				next_value = float( self.model.predict( last_window.reshape( 1, -1 ) )[ 0 ] )
				preds.append( next_value )
				last_window = np.roll( last_window, -1 )
				last_window[ -1 ] = next_value
			
			self.prediction = np.array( preds, dtype=float )
			return self.prediction
		except Exception as e:
			exception = Error( e )
			exception.module = 'mathy'
			exception.cause = 'LagQuantileSeries'
			exception.method = 'project( self, n_steps: int=1 ) -> np.ndarray | None'
			Logger( ).write( exception )
			raise exception
	
	def score( self ) -> float | None:
		"""Score fitted forecasts.

				Purpose:
				    Computes the coefficient of determination for fitted in-sample predictions against the stored training target values.

				Returns:
				    float | None: float | None returned by the forecasting operation.

				Raises:
				    Error: Raised when validation, model execution, forecasting, scoring, or diagnostic calculation fails.
		"""
		try:
			throw_if( 'training_data', self.training_data )
			throw_if( 'training_values', self.training_values )
			return float( self.model.score( self.training_data, self.training_values ) )
		except Exception as e:
			exception = Error( e )
			exception.module = 'mathy'
			exception.cause = 'LagQuantileSeries'
			exception.method = 'score( self ) -> float | None'
			Logger( ).write( exception )
			raise exception
	
	def analyze( self ) -> Dict[ str, float ] | None:
		"""Analyze forecast residuals.

				Purpose:
				    Computes regression diagnostics for fitted in-sample predictions, including squared error, absolute error, explained variance, maximum error, median absolute error, and coefficient of determination.

				Returns:
				    Dict[str, float] | None: Dict[str, float] | None returned by the forecasting operation.

				Raises:
				    Error: Raised when validation, model execution, forecasting, scoring, or diagnostic calculation fails.
		"""
		try:
			throw_if( 'training_values', self.training_values )
			
			if self.fitted_values is None:
				throw_if( 'training_data', self.training_data )
				self.fitted_values = self.model.predict( self.training_data )
			
			self.mean_absolute_error = mean_absolute_error(
				self.training_values,
				self.fitted_values
			)
			self.mean_squared_error = mean_squared_error(
				self.training_values,
				self.fitted_values
			)
			self.root_mean_squared_error = float(
				np.sqrt( self.mean_squared_error )
			)
			self.r2_score = r2_score(
				self.training_values,
				self.fitted_values
			)
			self.explained_variance_score = explained_variance_score(
				self.training_values,
				self.fitted_values
			)
			self.median_absolute_error = median_absolute_error(
				self.training_values,
				self.fitted_values
			)
			self.max_error = max_error(
				self.training_values,
				self.fitted_values
			)
			
			return {
					'MAE': float( self.mean_absolute_error ),
					'MSE': float( self.mean_squared_error ),
					'RMSE': float( self.root_mean_squared_error ),
					'R2': float( self.r2_score ),
					'EVS': float( self.explained_variance_score ),
					'MedianAE': float( self.median_absolute_error ),
					'MAX': float( self.max_error )
			}
		except Exception as e:
			exception = Error( e )
			exception.module = 'mathy'
			exception.cause = 'LagQuantileSeries'
			exception.method = 'analyze( self ) -> Dict[str, float] | None'
			Logger( ).write( exception )
			raise exception

class ARIMA( TimeSeries ):
	"""Forecast with ARIMA.

		Purpose:
		    Wraps statsmodels ARIMA for nonseasonal autoregressive integrated moving-average
		    forecasting. The wrapper stores the fitted results object, produces forward projections,
		    and reports regression-style diagnostics against fitted in-sample values.

		Attributes:
		    order: ARIMA autoregressive, differencing, and moving-average order.
		    model: statsmodels ARIMA model object created during training.
		    fitted: Fitted statsmodels results object returned by model fitting.
		    tranining_values: Source series used to fit the ARIMA model.
		    prediction: Most recent forecast output.
	"""
	order: Tuple[ int, int, int ]
	model: Optional[ am.ARIMA ]
	results: Optional[ am.ARIMAResults ]
	prediction: Optional[ np.ndarray ]
	train_data: Optional[ np.ndarray ]
	
	def __init__( self, order: Tuple[ int, int, int ] = (1, 0, 0) ) -> None:
		"""Initialize ARIMA forecaster.

				Purpose:
				    Configures the nonseasonal ARIMA order and prepares model, fitted-result, training-value, and prediction state for later forecasting.

				Args:
				    order: Autoregressive, differencing, and moving-average order.
		"""
		self.order = order
		self.model = None
		self.results = None
		self.prediction = None
		self.train_data = None
	
	def train( self, series: np.ndarray ) -> ARIMA | None:
		"""Fit ARIMA model.

				Purpose:
				    Fits the statsmodels ARIMA model to the supplied ordered series and stores the fitted results object for forecasting and diagnostics.

				Args:
				    series: Ordered univariate series used to fit the forecasting model.

				Returns:
				    ARIMA | None: ARIMA | None returned by the forecasting operation.

				Raises:
				    Error: Raised when validation, model execution, forecasting, scoring, or diagnostic calculation fails.
		"""
		try:
			throw_if( 'series', series )
			values = np.asarray( series, dtype=float ).reshape( -1 )
			if len( values ) <= max( self.order[ 0 ], self.order[ 2 ], 1 ):
				msg = 'Argument "series" doesnt contain enough observations for the selected ARIMA'
				raise ValueError( msg )
			
			self.train_data = values
			self.model = am.ARIMA( endog=self.train_data, order=self.order )
			self.results = self.model.fit( )
			return self
		except Exception as e:
			exception = Error( e )
			exception.module = 'mathy'
			exception.cause = 'ARIMA'
			exception.method = 'train( self, series: np.ndarray ) -> ARIMA | None'
			Logger( ).write( exception )
			raise exception
	
	def project( self, n_steps: int = 1 ) -> np.ndarray:
		"""Project future observations.

				Purpose:
				    Generates a forward forecast from the fitted statsmodels results object for the requested number of future periods.

				Args:
				    n_steps: Number of future periods to forecast.

				Returns:
				    np.ndarray: np.ndarray returned by the forecasting operation.

				Raises:
				    Error: Raised when validation, model execution, forecasting, scoring, or diagnostic calculation fails.
		"""
		try:
			throw_if( 'results', self.results )
			throw_if( 'n_steps', n_steps )
			if n_steps < 1:
				raise ValueError( 'Argument "n_steps" must be greater than zero.' )
			
			forecast = np.asarray( self.results.forecast( steps=n_steps ), dtype=float )
			self.prediction = forecast
			return self.prediction
		except Exception as e:
			exception = Error( e )
			exception.module = 'mathy'
			exception.cause = 'ARIMA'
			exception.method = 'project( self, n_steps: int=1 ) -> np.ndarray'
			Logger( ).write( exception )
			raise exception
	
	def score( self ) -> float | None:
		"""Score fitted forecasts.

				Purpose:
				    Computes the coefficient of determination for fitted in-sample values against the original training series.

				Returns:
				    float | None: float | None returned by the forecasting operation.

				Raises:
				    Error: Raised when validation, model execution, forecasting, scoring, or diagnostic calculation fails.
		"""
		try:
			throw_if( 'train_data', self.train_data )
			throw_if( 'results', self.results )
			y_pred = np.asarray( self.results.fittedvalues, dtype=float ).reshape( -1 )
			y_true = np.asarray( self.train_data, dtype=float ).reshape( -1 )
			if len( y_pred ) == 0:
				raise ValueError( 'ARIMA fitted values are empty.' )
			
			y_true = y_true[ -len( y_pred ): ]
			return float( r2_score( y_true, y_pred ) )
		except Exception as e:
			exception = Error( e )
			exception.module = 'mathy'
			exception.cause = 'ARIMA'
			exception.method = 'score( self ) -> float | None'
			Logger( ).write( exception )
			raise exception
	
	def analyze( self ) -> Dict[ str, float ] | None:
		"""Analyze forecast residuals.

				Purpose:
				    Computes regression diagnostics for fitted in-sample values against the original training series, including squared error, absolute error, explained variance, maximum error, median absolute error, and coefficient of determination.

				Returns:
				    Dict[str, float] | None: Dict[str, float] | None returned by the forecasting operation.

				Raises:
				    Error: Raised when validation, model execution, forecasting, scoring, or diagnostic calculation fails.
		"""
		try:
			throw_if( 'train_data', self.train_data )
			throw_if( 'results', self.results )
			y_pred = np.asarray( self.results.fittedvalues, dtype=float ).reshape( -1 )
			y_true = np.asarray( self.train_data, dtype=float ).reshape( -1 )
			if len( y_pred ) == 0:
				raise ValueError( 'ARIMA fitted values are empty.' )
			
			y_true = y_true[ -len( y_pred ): ]
			return {
					'MSE': mean_squared_error( y_true, y_pred ),
					'RMSE': np.sqrt( mean_squared_error( y_true, y_pred ) ),
					'MAE': mean_absolute_error( y_true, y_pred ),
					'MedianAE': median_absolute_error( y_true, y_pred ),
					'R2': r2_score( y_true, y_pred ),
					'ExplainedVariance': explained_variance_score( y_true, y_pred )
			}
		except Exception as e:
			exception = Error( e )
			exception.module = 'mathy'
			exception.cause = 'ARIMA'
			exception.method = 'analyze( self ) -> Dict[str, float] | None'
			Logger( ).write( exception )
			raise exception

class SARIMA( TimeSeries ):
	"""Forecast with SARIMA.

		Purpose:
			Wraps statsmodels SARIMAX for seasonal autoregressive integrated moving-average
			forecasting. The wrapper stores the fitted seasonal model, produces forward projections,
			and reports regression-style diagnostics against fitted in-sample values.

		Attributes:
			order: Nonseasonal autoregressive, differencing, and moving-average order.
			seasonal: Seasonal ARIMA order and period specification.
			model: statsmodels SARIMAX model object created during training.
			fitted: Fitted statsmodels results object returned by model fitting.
			tranining_values: Source series used to fit the SARIMA model.
			prediction: Most recent forecast output.
	"""
	order: Tuple[ int, int, int ]
	seasonal_order: Tuple[ int, int, int, int ]
	model: Optional[ st.SARIMAX ]
	results: Optional[ st.SARIMAXResults ]
	training_data: Optional[ np.ndarray ]
	prediction: Optional[ np.ndarray ]
	
	def __init__( self, order: Tuple[ int, int, int ] = (1, 1, 1),
			seasonal: Tuple[ int, int, int, int ] = (0, 0, 0, 0) ) -> None:
		"""Initialize SARIMA forecaster.

				Purpose:
					Configures nonseasonal and seasonal SARIMA orders and prepares model, fitted-result, training-value, and prediction state for later forecasting.

				Args:
					order: Nonseasonal autoregressive, differencing, and moving-average order.
					seasonal: Seasonal autoregressive, differencing, moving-average, and period order.
		"""
		self.order = order
		self.seasonal_order = seasonal
		self.model = None
		self.results = None
		self.training_data = None
		self.prediction = None
	
	def train( self, series: np.ndarray ) -> SARIMA | None:
		"""Fit SARIMA model.

				Purpose:
					Fits the statsmodels SARIMA model to the supplied ordered series and stores the fitted results object for forecasting and diagnostics.

				Args:
					series: Ordered univariate series used to fit the forecasting model.

				Returns:
					SARIMA | None: SARIMA | None returned by the forecasting operation.

				Raises:
					Error: Raised when validation, model execution, forecasting, scoring, or diagnostic calculation fails.
		"""
		try:
			throw_if( 'series', series )
			values = np.asarray( series, dtype=float ).reshape( -1 )
			min_obs = max( self.order[ 0 ] + self.order[ 1 ] + self.order[ 2 ],
			               self.seasonal_order[ 0 ] + self.seasonal_order[ 1 ] +
			               self.seasonal_order[ 2 ], 1 )
			if len( values ) <= min_obs:
				msg = 'Argument "series" doesnt contain enough observations for the selected SARIMA'
				raise ValueError( msg )
			
			self.training_data = values
			self.model = st.SARIMAX( endog=self.training_data, order=self.order,
				seasonal_order=self.seasonal_order, enforce_stationarity=False,
				enforce_invertibility=False )
			self.results = self.model.fit( disp=False )
			return self
		except Exception as e:
			exception = Error( e )
			exception.module = 'mathy'
			exception.cause = 'SARIMA'
			exception.method = 'train( self, series: np.ndarray ) -> SARIMA | None'
			Logger( ).write( exception )
			raise exception
	
	def project( self, n_steps: int = 1 ) -> np.ndarray:
		"""Project future observations.

				Purpose:
					Generates a forward forecast from the fitted statsmodels results object for the requested number of future periods.

				Args:
					n_steps: Number of future periods to forecast.

				Returns:
					np.ndarray: np.ndarray returned by the forecasting operation.

				Raises:
					Error: Raised when validation, model execution, forecasting, scoring, or diagnostic calculation fails.
		"""
		try:
			throw_if( 'results', self.results )
			throw_if( 'n_steps', n_steps )
			if n_steps < 1:
				raise ValueError( 'Argument "n_steps" must be greater than zero.' )
			
			forecast = np.asarray( self.results.forecast( steps=n_steps ), dtype=float )
			self.prediction = forecast
			return self.prediction
		except Exception as e:
			exception = Error( e )
			exception.module = 'mathy'
			exception.cause = 'SARIMA'
			exception.method = 'project( self, n_steps: int=1 ) -> np.ndarray'
			Logger( ).write( exception )
			raise exception
	
	def score( self ) -> float | None:
		"""Score fitted forecasts.

				Purpose:
					Computes the coefficient of determination for fitted in-sample values against the original training series.

				Returns:
					float | None: float | None returned by the forecasting operation.

				Raises:
					Error: Raised when validation, model execution, forecasting, scoring, or diagnostic calculation fails.
		"""
		try:
			throw_if( 'training_data', self.training_data )
			throw_if( 'results', self.results )
			y_pred = np.asarray( self.results.fittedvalues, dtype=float ).reshape( -1 )
			y_true = np.asarray( self.training_data, dtype=float ).reshape( -1 )
			if len( y_pred ) == 0:
				raise ValueError( 'SARIMA fitted values are empty.' )
			
			y_true = y_true[ -len( y_pred ): ]
			return float( r2_score( y_true, y_pred ) )
		except Exception as e:
			exception = Error( e )
			exception.module = 'mathy'
			exception.cause = 'SARIMA'
			exception.method = 'score( self ) -> float | None'
			Logger( ).write( exception )
			raise exception
	
	def analyze( self ) -> Dict[ str, float ] | None:
		"""Analyze forecast residuals.

				Purpose:
					Computes regression diagnostics for fitted in-sample values against the original training series, including squared error, absolute error, explained variance, maximum error, median absolute error, and coefficient of determination.

				Returns:
					Dict[str, float] | None: Dict[str, float] | None returned by the forecasting operation.

				Raises:
					Error: Raised when validation, model execution, forecasting, scoring, or diagnostic calculation fails.
		"""
		try:
			throw_if( 'training_data', self.training_data )
			throw_if( 'results', self.results )
			y_pred = np.asarray( self.results.fittedvalues, dtype=float ).reshape( -1 )
			y_true = np.asarray( self.training_data, dtype=float ).reshape( -1 )
			if len( y_pred ) == 0:
				raise ValueError( 'SARIMA fitted values are empty.' )
			
			y_true = y_true[ -len( y_pred ): ]
			return {
					'MSE': mean_squared_error( y_true, y_pred ),
					'RMSE': np.sqrt( mean_squared_error( y_true, y_pred ) ),
					'MAE': mean_absolute_error( y_true, y_pred ),
					'MedianAE': median_absolute_error( y_true, y_pred ),
					'R2': r2_score( y_true, y_pred ),
					'ExplainedVariance': explained_variance_score( y_true, y_pred )
			}
		except Exception as e:
			exception = Error( e )
			exception.module = 'mathy'
			exception.cause = 'SARIMA'
			exception.method = 'analyze( self ) -> Dict[str, float] | None'
			Logger( ).write( exception )
			raise exception


   
