[theme]
base = 'dark'
backgroundColor = '#141414'
secondaryBackgroundColor = '#7D7C7C'
textColor = '#FFFFFF'
dataframeBorderColor = '#2CB7DE'
primaryColor = '#3594FC'
borderColor = '#8C8B8C'
dataframeHeaderBackgroundColor = '#023770'
font = 'Roboto Regular'
baseFontSize = 11
